### ISSUE TITLE
Open XAL Meeting

### ISSUE THREAD

**Issue by dreadmill** [openxal/openxal#6]
Hello Everyone,

I am proposing we have a short Open XAL meeting next week Thursday at 9:00 EDT (August 11 at 3:00 CEST).  If that date/time is terribly inconvenient we can move it of course.

I have been back full time for a couple months now.  And we have just hired Sasha Zhukov to head up our high-level applications, of which Open XAL is a major part.  Thus, now that our sides is up and running again seems as it would be a good idea to check in and see what everyone is doing.

Look forward to seeing you all again.
Chris

**Comment by azukov** [comment]
Here is a brief summary of what we discussed during the meeting.
Comments and suggestions are welcome!
[OpenXalCollaborationActivities-Aug25.pdf](https://github.com/openxal/openxal/files/439926/OpenXalCollaborationActivities-Aug25.pdf)
